= Panaeolus User's Guide
:author: Hlöðver Sigurðsson
:revdate: August 2, 2019
:revnumber: 1.0.0
:lang: en
:encoding: UTF-8
:doctype: book
:source-highlighter: coderay
:source-language: clojure
:toc: left
:toclevels: 3
:sectlinks:
:sectanchors:
:leveloffset: 1
:sectnums:
:scriptsdir: js
:overtone-version: 0.10.3
:imagesdir: media/docs_img
:imagesoutdir: media/docs_img

ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

++++
<link rel="stylesheet"  href="http://cdnjs.cloudflare.com/ajax/libs/font-awesome/3.1.0/css/font-awesome.min.css">
++++

:icons: font

ifdef::env-github[]
toc::[]
endif::[]

= Introduction

*Panaeolus* is a library with an editor that enables straightforward real-time pattern making with Csound.


= PanaeolusEditor Installation

== Windows

You may need to install:

- Visual C++ redistributeable https://aka.ms/vs/16/release/vc_redist.x64.exe

== MacOs

You're going to need jack audio connection kit, but as of this writing DO NOT install it from the package manager Brew.

Copy the jack2 binary from here: http://jackaudio.org/downloads/


= Csound and Panaeolus

To connect your Csound instruments and effects to Panaeolus you will need to define them with `definst` or `define-fx` respectively.
These are macros written in Clojure, so depending on how you use Panaeolus, you may or may not need to import them into your namespace.

== definst

```Clojure
(require '[panaeolus.csound.macros :refer [definst]])
;; or alternatively as part of namespace decleration
(ns my-namespace
  (:require [panaeolus.csound.macros :refer [definst]]))
```
